# SPDX-License-Identifier: MIT
---
- name: Check cluster configuration variables
  block:
    - name: Fail if passwords are not specified
      fail:
        msg: "{{ item }} must be specified"
      when: lookup("vars", item, default="") | length < 1
      loop:
        - ha_cluster_hacluster_password
      run_once: yes

    - name: Fail if nodes do not have the same number of SBD devices specified
      fail:
        msg: All nodes must have the same number of SBD devices specified
      when:
        - ha_cluster_sbd_enabled
        - >
          ansible_play_hosts_all
          | map('extract', hostvars, ['ha_cluster', 'sbd_devices'])
          | map('default', [], true)
          | map('length') | unique | length > 1
      run_once: yes
  when: ha_cluster_cluster_present

- name: Discover cluster node names
  set_fact:
    __ha_cluster_node_name: "{{
        ha_cluster.node_name | default(inventory_hostname)
      }}"

- name: Collect cluster node names
  set_fact:
    __ha_cluster_all_node_names: "{{
        ansible_play_hosts_all
        | map('extract', hostvars, '__ha_cluster_node_name')
        | list
      }}"
