- name: Check cluster configuration variables
  block:
    - name: Fail if passwords or authkeys are not specified
      fail:
        msg: "{{ item }} must be specified"
      when: lookup("vars", item, default="") | length < 1
      loop:
        - ha_cluster_hacluster_password
        - ha_cluster_authkey_corosync_path
        - ha_cluster_authkey_pacemaker_path
      run_once: yes

    - name: Fail if fence-virt is installed with no authkey specified
      fail:
        msg: "ha_cluster_authkey_fence_virt_path must be specified if fence-virt is installed"
      when:
        - ha_cluster_authkey_fence_virt_path | length < 1
        - "'fence-virt' in ha_cluster_fence_agent_packages"
      run_once: yes
  when: ha_cluster_cluster_present

- name: Extract all node names
  set_fact:
    ha_cluster_internal_node_name: "{{ \
        hostvars[item].ha_cluster.node_name | default(item) \
      }}"
  loop: "{{ ansible_play_hosts }}"
  run_once: yes
  register: ha_cluster_internal_node_name_result

- name: Collect all node names
  set_fact:
    ha_cluster_internal_all_node_names: "{{
        ha_cluster_internal_node_name_result.results \
        | map(attribute='ansible_facts.ha_cluster_internal_node_name') \
        | list \
      }}"
  run_once: yes
