- name: Enable or disable configured cluster services on boot
  service:
    name: "{{ item }}"
    enabled: "{{ ha_cluster_start_on_boot }}"
  loop:
    - corosync
    - corosync-qdevice
    - pacemaker
  when:
    - ha_cluster_start_on_boot != "nochange"
    - item != "corosync-qdevice" or ha_cluster_internal_qdevice_in_use

- name: Get services status - detect SBD
  service_facts:

# The role does not support configuring SBD yet, therefore we always disable it.
- name: Enable or disable SBD
  service:
    name: "sbd"
    enabled: no
  when:
    - '"sbd.service" in ansible_facts.services'
