- name: Create a corosync.conf tempfile
  tempfile:
    state: file
    suffix: _ha_cluster_corosync_conf
  register: ha_cluster_internal_tempfile_corosync_conf
  run_once: yes
  # We always need to create corosync.conf file to see whether it's the same as
  # what is already present on the cluster nodes. However, we don't want to
  # report it as a change since the only thing which matters is copying the
  # resulting corosync.conf to cluster nodes.
  check_mode: no
  changed_when: not ansible_check_mode

- name: Create a corosync.conf file content
  include_tasks: "cluster-setup-{{ ha_cluster_pcs_provider }}.yml"

- name: Fetch created corosync.conf file
  slurp:
    src: "{{ ha_cluster_internal_tempfile_corosync_conf.path }}"
  register: ha_cluster_internal_data_corosync_conf
  run_once: yes
  when: ha_cluster_internal_tempfile_corosync_conf.path is defined

- name: Distribute corosync.conf file
  copy:
    content: "{{ ha_cluster_internal_data_corosync_conf['content'] | b64decode }}"
    dest: /etc/corosync/corosync.conf
    owner: "root"
    group: "root"
    mode: "0644"
  register: ha_cluster_internal_distribute_corosync_conf
  when: ha_cluster_internal_data_corosync_conf is defined

- name: Remove a corosync.conf tempfile
  file:
    path: "{{ ha_cluster_internal_tempfile_corosync_conf.path }}"
    state: absent
  when: ha_cluster_internal_tempfile_corosync_conf.path is defined
  run_once: yes
  # We always need to create corosync.conf file to see whether it's the same as
  # what is already present on the cluster nodes. However, we don't want to
  # report it as a change since the only thing which matters is copying the
  # resulting corosync.conf to cluster nodes.
  check_mode: no
  changed_when: not ansible_check_mode

- name: Distribute corosync authkey
  copy:
    src: "{{ ha_cluster_authkey_corosync_path }}"
    dest: /etc/corosync/authkey
    owner: "root"
    group: "root"
    mode: "0400"

- name: Distribute pacemaker authkey
  copy:
    src: "{{ ha_cluster_authkey_pacemaker_path }}"
    dest: /etc/pacemaker/authkey
    owner: "hacluster"
    group: "haclient"
    mode: "0400"
