- name: Check if qdevice is configured
  command:
    cmd: pcs quorum config
  register: HA_Cluster_internal_pcs_quorum_config
  run_once: true
  check_mode: no
  changed_when: false

- name: Enable or disable configured cluster services on boot
  service:
    name: "{{ item }}"
    enabled: "{{ (HA_Cluster_start_on_boot == 'yes') | ternary(true, false) }}"
  loop:
    - corosync
    - corosync-qdevice
    - pacemaker
  when: item != "corosync-qdevice" or "Device:" in HA_Cluster_internal_pcs_quorum_config.stdout_lines

