- name: Enable standard repositories
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop: "{{ __ha_cluster_repos }}"
  when:
    - ha_cluster_enable_repos
  ignore_errors: yes

- name: Install cluster packages
  package:
    name: "{{ \
      __ha_cluster_fullstack_node_packages \
      + \
      ha_cluster_fence_agent_packages \
    }}"
    state: present

# The user is created by installing pacemaker packages. We just need to set the
# password.
- name: Set hacluster password
  user:
    name: "hacluster"
    password: "{{ \
      ha_cluster_hacluster_password | \
      password_hash('sha512', ansible_hostname|replace('-','x')) \
    }}"
