# SPDX-License-Identifier: MIT
---
- name: Remove cluster configuration
  include_tasks: "cluster-destroy-{{ HA_Cluster_pcs_provider }}.yml"
  when: HA_Cluster_cluster_present == "no"

- name: Configure cluster nodes
  include_tasks: cluster-setup.yml
  when: HA_Cluster_cluster_present == "yes"

- name: Pcs auth
  # Auth is run after corosync.conf has been distributed so that pcs
  # distributes pcs tokens in the cluster automatically.
  include_tasks: pcs-auth.yml
  when: HA_Cluster_cluster_present == "yes"
