# SPDX-License-Identifier: MIT
---
- name: Remove cluster configuration
  include_tasks: "cluster-destroy-{{ ha_cluster_pcs_provider }}.yml"
  when: not ha_cluster_cluster_present

- name: Install and configure HA cluster
  block:
    - name: Check and prepare role variables
      include_tasks: check-and-prepare-role-variables.yml

    - name: Configure pcs / pcsd
      include_tasks: pcs-configure-pcs-pcsd.yml

    - name: Configure cluster nodes
      include_tasks: cluster-setup.yml

#    TODO: implement qdevice detection once qdevice is supported by the role
#    - name: Fetch corosync quorum configuration
#      command:
#        cmd: pcs quorum config
#      register: ha_cluster_internal_pcs_quorum_config
#      run_once: yes
#      check_mode: no
#      changed_when: no
#      # This reads corosync.conf from the nodes. The file is not sent to the
#      # nodes in check mode.
#      when: not ansible_check_mode
    - name: Check if qdevice is configured
      set_fact:
        ha_cluster_internal_qdevice_in_use: no
      run_once: yes

    - name: Enable or disable cluster services on boot
      include_tasks: cluster-enable-disable.yml
      when: ha_cluster_start_on_boot != "nochange"

    - name: Pcs auth
      # Auth is run after corosync.conf has been distributed so that pcs
      # distributes pcs tokens in the cluster automatically.
      include_tasks: pcs-auth.yml

    - name: Start the cluster and reload corosync.conf
      include_tasks: cluster-start-and-reload.yml
  when: ha_cluster_cluster_present
