- name: Check pcs auth status
  command:
    # TODO switch to inventory variables: node names and addresses
    cmd: pcs status pcsd {% for node in ansible_play_hosts %} "{{ node|quote }}" {% endfor %}
  register: HA_Cluster_internal_pcs_auth_status
  check_mode: no
  # rc == 0 means all nodes are authenticated
  # rc == 2 means not all nodes are authenticated
  # any other rc means an error
  changed_when: HA_Cluster_internal_pcs_auth_status.rc == 2
  failed_when:
    - HA_Cluster_internal_pcs_auth_status.rc != 0
    - HA_Cluster_internal_pcs_auth_status.rc != 2

- name: Run pcs auth
  include_tasks: "pcs-auth-{{ HA_Cluster_pcs_provider }}.yml"
  when: not ansible_check_mode and HA_Cluster_internal_pcs_auth_status.rc == 2
