- name: Distribute pcsd SSL private key
  copy:
    src: "{{ HA_Cluster_pcsd_SSL_cert.private }}"
    dest: /var/lib/pcsd/pcsd.key
    owner: "root"
    group: "root"
    mode: "0600"
  register: HA_Cluster_internal_send_pcs_ssl_key

- name: Distribute pcsd SSL certificate
  copy:
    src: "{{ HA_Cluster_pcsd_SSL_cert.public }}"
    dest: /var/lib/pcsd/pcsd.crt
    owner: "root"
    group: "root"
    mode: "0600"
  register: HA_Cluster_internal_send_pcs_ssl_cert

- name: Restarting pcsd to reload its SSL certificate
  service:
    name: pcsd
    state: restarted
  when: HA_Cluster_internal_send_pcs_ssl_key.changed or HA_Cluster_internal_send_pcs_ssl_cert.changed
