# Pcsd must be stopped when its config files are being updated. This is to
# prevent a race condition caused by pcsd syncing its files in the cluster on
# its own.
- name: Stop pcsd
  service:
    name: pcsd
    state: stopped

- name: Distribute pcsd TLS certificate and key
  block:
    - name: Distribute pcsd TLS private key
      copy:
        src: "{{ ha_cluster_pcsd_private_key_src }}"
        dest: /var/lib/pcsd/pcsd.key
        owner: "root"
        group: "root"
        mode: "0600"
    - name: Distribute pcsd TLS certificate
      copy:
        src: "{{ ha_cluster_pcsd_public_key_src }}"
        dest: /var/lib/pcsd/pcsd.crt
        owner: "root"
        group: "root"
        mode: "0600"
  when:
    - ha_cluster_pcsd_public_key_src | length < 1
    - ha_cluster_pcsd_private_key_src | length < 1

- name: Distribute pcs_settings.conf
  template:
    src: templates/pcs_settings.conf
    dest: /var/lib/pcsd/pcs_settings.conf
    owner: "root"
    group: "root"
    mode: "0644"
    trim_blocks: no

- name: Start pcsd with updated config files
  service:
    name: pcsd
    state: started
