# SPDX-License-Identifier: MIT
---
- name: Check SBD device headers
  command: "sbd -d {{ item }} dump"
  run_once: true
  ignore_errors: true
  changed_when: false
  register: "sbd_dump"
  loop: "{{ ha_cluster_sbd_devices }}"
  when:
    - ha_cluster_sbd_devices

- name: Create SBD devices
  command: sbd -d {{ item.item }} {{ ha_cluster_sbd_create_params }} create
  loop: "{{ sbd_dump['results'] }}"
  when:
    - item.rc == 1
    - ha_cluster_sbd_devices
  run_once: true

- name: Enable softdog module
  copy:
    content: softdog
    dest: /etc/modules-load.d/softdog.conf
    owner: root
    group: root
    mode: '0644'
  notify: Load softdog module

- name: Create SBD configuration file
  template:
    src: templates/sbd.j2
    dest: /etc/sysconfig/sbd
    owner: root
    group: root
    mode: '0644'
  when: ha_cluster_sbd_devices

- name: Enable SBD
  service:
    name: sbd
    enabled: true

# TODO: automatically create stonith fence resources
#       e.g. via pcs-cib-resource-create-pcs-0.10.yml?
